//
// Created by Byakuya on 2026/8/8.
//

#ifndef USERACTIVATOR_CONFIGURATION_H
#define USERACTIVATOR_CONFIGURATION_H

const int LOGIN_FAIL_THRESHOLD = 5;

#endif //USERACTIVATOR_CONFIGURATION_H
