//
// Created by Work on 2026/8/5.
//

#ifndef LIBUSERACTIVITYMONITOR_GENERIC_CONFIGURATION_H
#define LIBUSERACTIVITYMONITOR_GENERIC_CONFIGURATION_H

const bool SMTP_FEATURE_ENABLED = true;

const bool EVERY_LOGIN_PROCEED_AN_EMAIL = true;

extern const char* ACTIVATE_ALL_USER_SCHEDULED_TASKNAME;

#endif //LIBUSERACTIVITYMONITOR_GENERIC_CONFIGURATION_H
